class QuizModel{
  String q;
  String a;
  String b;
  String c;
  String d;
  String e;
  QuizModel({required this.q,required this.a,required this.b,required this.c,required this.d,required this.e});


}
List quiz=[
  QuizModel(q: "The one measurement of fetal maturity that is not affected by a 'bloody tap' during amniocentesis is?", a: "L/S ratio", b:"Phosphatidyl glycerol" , c: "Alpha-fetoproetein ", d: "Bilirubin as measured by ∆ OD 450", e: "Phosphatidyl glycerol"),
  QuizModel(q: "Which of the following is not true regarding congenital torticollis?", a: "It undergoes spontaneous resolution", b: "In 2/3rd cases, sternomastoid mass is palpable", c: "Plagiocephaly", d: "Always associated with breech extraction", e: "Always associated with breech extraction"),
  QuizModel(q: "A woman has been diagnosed with high risk gestational trophoblastic neoplasia and is about to receive multi-agent chemotherapy. What is the expected cure rate ? ", a: "65%", b: "75%", c: "85%", d: "95%", e: "95%"),
  QuizModel(q: "While operating on a patient in a lithotomy position, the padding between the lateral fibular head and stirrup prevents injury to:", a: "Common peroneal nerve", b: "Lateral cutaneous nerve of thigh", c: "Tibial nerve", d: "Pudendal nerve", e: "Common peroneal nerve"),
  QuizModel(q: "A PG with twin pregnancy has booked for antenatal care at 16 weeks of gestation. Despite referral to higher centre, the chorionicity of the pregnancy could not be established by ultrasound. Fetal growth is within normal range and there are no obvious structural defects. What is the best option for further antenatal management in this case?", a: "Amniocentesis to determine fetal karyotyping", b: "Chorionic villus sampling for fetal genotyping", c: "Empirically manage as dichorionic twins as this is commoner", d: "Empirically manage as monochorionic twins", e: "Empirically manage as monochorionic twins"),
  QuizModel(q: "A 32-year-old woman who has cycles of 7/28 with heavy and painful periods presents with one year history of second infertility. She used an IUCD subsequently which has to be removed because of lower abdominal pain and offensive discharge. Her partner of two years has three children from two previous relationships: ", a: "Free androgen index", b: "Semen analysis", c: "Laparoscopy and dye test", d: "FBC", e: "Laparoscopy and dye test"),
  QuizModel(q: "Osnate-D is indicated in which of the following conditions?", a: "Increased mineral requirements during pregnancy, lactation and growth", b: "Osteoporosis", c: "Osteopenia", d: "All of the above", e: "All of the above"),
  QuizModel(q: "Which of the following ovarian tumour is most prone to undergo torsion during pregnancy?",  a: "Serous cystadenoma", b: "Mucinous cystadenoma", c: "Dermoid cyst", d: "None of above", e: "Serous cystadenoma"),
  QuizModel(q: "The intersecting lines drawn on maps and globes are?", a: "Latitudes", b: "Longitudes", c: "Geographic grids", d: "None of above", e: "Geographic grids"),
  QuizModel(q: "Who invented the ballpoint pen?", a: "Biro Brothers", b: "Waterman Brothers", c: "Bicc Brothers", d: "Write Brothers", e: "Biro Brothers"),
  QuizModel(q: "The time duration for healing of LSCS by primary intention to reach full tensile strength is:", a: "3 weeks", b: "6 weeks", c: "12 weeks", d: "24 weeks", e: "12 weeks"),
  QuizModel(q: "Which of the following statements is true about hyperthyroidism in pregnancy?", a: "During pregnancy treatment should be aimed at keeping the thyroid hormones at the lower limit of normal range", b: "fetal hyperthyroidism is a common complication in these patients", c: "pregnancy worsens thyroid status especially in the third trimester ", d: "Propylthiouracil and carbimazole can be safely continued in pregancy", e: "Propylthiouracil and carbimazole can be safely continued in pregancy"),
  QuizModel(q: "65 years total abdominal hysterectomy and bilateral oophorectomy for grade-1 endometrial cancer. The final histology report confirms the tumor invading the uterine serosa. As per new FIGO staging of endometrial cancer, what is the stage?", a: "stage 1 C", b: "stage 2 C", c: "stage 3 A", d: "stage 3 B", e: "stage 3 A"),
  QuizModel(q: "The following are the statements relating to IUGR and SGA. Which of the following statement is correct?", a: "All fetuses that are IUGR are in less than the 10th percentile for estimated gestational age specific fetal weight.", b: "All fetuses that are SGA are IUGR.", c: "Constitutionally small SGA fetuses are at increased risk of antepartum stillbirth.", d: "SGA is defined as growth at the 10th or less percentile for weight of all fetuses at the gestational age.", e: "SGA is defined as growth at the 10th or less percentile for weight of all fetuses at the gestational age."),
  QuizModel(q: "44-year-old woman, gravida 4, para 3, at 8 weeks gestation has mild nausea and vomiting. Her obstetric history is significant for three full-term, normal vaginal deliveries of normal infants. Physical examination reveals an 8-week-sized uterus but is otherwise unremarkable. She wishes to have chromosomal testing of the fetus and wants to have chorionic villus sampling performed. Compared with amniocentesis, chorionic villus sampling may place the patient at a greater risk for which of the following?", a: "Fetal down syndrome", b: "Fetal limb defects", c: "Fetal neural tube defects", d: "Maternal sepsis", e: "Fetal limb defects"),
  QuizModel(q: "A 33-year-old primigravida at 18 weeks of gestation comes to the physician for a prenatal visit. Her prenatal course has been uncomplicated thus far. She has hypothyroidism, for which she takes thyroid hormone replacement. The patient states that a friend of hers recently had a preterm delivery. The patient is quite concerned about preterm delivery and wants to know whether home uterine activity monitoring (HUAM) is recommended. Which of the following is the most appropriate response? ", a: "HUAM has been proven to cause preterm birth", b: "HUAM has been proven to prevent preterm birth", c: "HUAM has not been proven to prevent preterm birth", d: "HUAM should be started immediately", e: "HUAM has not been proven to prevent preterm birth"),
];